apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-flask
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-flask
  template:
    metadata:
      labels:
        app: alertmanager-flask
    spec:
      containers:
        - name: alertmanager-flask
          image: <your-dockerhub-username>/alert-manager:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-flask
  namespace: monitoring
spec:
  selector:
    app: alertmanager-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
